### ISSUE TITLE
Pin as numeric keypad

### ISSUE THREAD

**Issue by criticallimit** [iantrich/restriction-card#62]
I´m using a wall mounted ipad for HA and protect some switches with restriction-card.
Whenever I unlock a switch with a pin protection the normal keyboard appears because it expects text (I think).
Would be very nice that only the numneric keypad would be opened for numbers input.

Can I change this? whenever a numeric pin is needed, the numeric keypad will open instead of the normal big keypad?

thanx

**Comment by flixlix** [comment]
I would also like this feature. I have two wall mounted Fire Tablet 10 running Fully Kiosk Browser, and at the moment, it's not very user friendly to always change to numerica keypads. I'm available for testing

**Comment by user897943** [comment]
Isn't it possible to build a card that pops up instead of an input box? The card could have a keypad like:
7 8 9
4 5 6
1 2 3
   0
Kinda like the lovelace alarm keypad...

**Comment by johntdyer** [comment]
yea, this is exactly what I am looking for....  I have wall mounted tablets too, and going to the keyboard for pin kinda sucks

**Comment by johntdyer** [comment]
@flixlix  did you ever find a solution for your tablet?

**Comment by johntdyer** [comment]
@iantrich  any thoughts on where this stacks up on the roadmap for this project ?  Wish I was capable with CSS otherwise I would give it a go myself...

**Comment by johntdyer** [comment]
@iantrich  also tried to buy you some coffees but link on this repo is broken...

**Comment by eric1905** [comment]
I would also be glad if it is possible to define a parameter like numeric and then I can input numbers directly instead of first switching to numbers

**Comment by johntdyer** [comment]
This feature is so needed !!

**Comment by vazquezjm** [comment]
Please, make it happen! 🙏

**Comment by swampylee** [comment]
I agree. This would be awesome if it were available.

**Comment by Fusseldieb** [comment]
This is _not possible_ with a vanilla JS input dialog.

Meaning that _iantrich_ would need to implement a third-party dialog, which could get messy very quick.

**Comment by ildar170975** [comment]
I wonder if it is possible to use a standard HA keypad?
https://github.com/home-assistant/frontend/pull/19969

**Comment by fiste788** [comment]
implemented in #115

**Comment by eric1905** [comment]
Great work, thank you. Let's hope that there will be a new release soon.

**Comment by eric1905** [comment]
@fiste788 
As there is no progress, do I have any possibility to already use it in my home assistance instance.

**Comment by fiste788** [comment]
> @fiste788 
> As there is no progress, do I have any possibility to already use it in my home assistance instance.

You can Copy and paste the content of restriction-card.ts in your installation of home assistant and then gzip the file

**Comment by eric1905** [comment]
> > @fiste788
> > As there is no progress, do I have any possibility to already use it in my home assistance instance.
> 
> You can Copy and paste the content of restriction-card.ts in your installation of home assistant and then gzip the file

Do I have to enable your implementation? I gzipped the file and replaced the 2 existing files in www/community/restriction-card with restriction-card.js and restriction-card.js.gz but it looks still like the same

**Comment by ildar170975** [comment]
Solved in https://github.com/iantrich/restriction-card/pull/115
All credits to @fiste788

**Comment by johntdyer** [comment]
@fiste788  you are my hero ! Thank you

**Comment by saoescape** [comment]
Hi, how can I activate the screen for the pin as in the picture?

**Comment by ildar170975** [comment]
>  how can I activate the screen for the pin as in the picture?

This dialog is shown when a pin input is needed.

**Comment by Nisbo** [comment]
> > how can I activate the screen for the pin as in the picture?
> 
> This dialog is shown when a pin input is needed.

I updated to 1.2.15, cleared the cache but I still get the JavaScript prompt

**Comment by ildar170975** [comment]
> but I still get the JavaScript prompt

Please post a screenshot.
Also, press F12 to get a Code Inspector (or whatever it is called in your browser) to check what version of a card is used.

**Comment by Nisbo** [comment]
![Image](https://github.com/user-attachments/assets/6adedc08-be3b-421b-aa1e-b41ded60f314)

Version:

![Image](https://github.com/user-attachments/assets/dab113ee-42a7-454f-a4ef-8bbc4aa822a3)


Browser: Firefox 134.0.2 (64-Bit)

**Comment by Nisbo** [comment]
Ups, I think I am using an other addon

```
card:
  type: custom:love-lock-card
  popup: password
  password: 
```
